"""Add is_deleted field for soft delete

Revision ID: 14417fbb7e31
Revises: 86324fe7536f
Create Date: 2025-07-29 19:45:39.795739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14417fbb7e31'
down_revision = '86324fe7536f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
