"""Convert status to enum type

Revision ID: 86324fe7536f
Revises: 3ae7e1df3099
Create Date: 2025-07-29 19:23:05.778912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86324fe7536f'
down_revision = '3ae7e1df3099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('BACKLOG', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'WONT_DO', name='taskstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'backlog'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('BACKLOG', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'WONT_DO', name='taskstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'backlog'"))

    # ### end Alembic commands ###
