"""Add due_date column to task table

Revision ID: a0eb4dc50c91
Revises: 14417fbb7e31
Create Date: 2025-08-05 18:48:40.867405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0eb4dc50c91'
down_revision = '14417fbb7e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_new')
    op.drop_table('user_new')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('id_uuid')
        batch_op.drop_column('user_id_uuid')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('id_uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_uuid', sa.VARCHAR(length=36), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id_uuid', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('id_uuid', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_column('due_date')

    op.create_table('user_new',
    sa.Column('id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_new',
    sa.Column('id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('why', sa.TEXT(), nullable=True),
    sa.Column('what', sa.TEXT(), nullable=True),
    sa.Column('how', sa.TEXT(), nullable=True),
    sa.Column('acceptance_criteria', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'backlog'"), nullable=False),
    sa.Column('sort_order', sa.FLOAT(), server_default=sa.text('(1000.0)'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_new.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
